FROM ubuntu:latest AS builder
RUN apt-get update && apt-get install -y python3 python3-pip
COPY . /
RUN python3 -m pip install .

FROM ubuntu:latest
COPY --from=builder /app/app.py .
CMD ["python3", "app.py"]